import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:vaulta/core/money/money.dart';
import 'package:vaulta/core/money/money_formatter.dart';
import 'package:vaulta/features/accounts/domain/entities/account.dart';
import 'package:vaulta/features/accounts/domain/entities/statement.dart';
import 'package:vaulta/features/accounts/presentation/widgets/account_visuals.dart';

/// Renders an account statement as an A4 PDF using the app's own Inter
/// faces (bundled font assets), so the document matches the brand.
///
/// Statements print on paper, so this is the one deliberately light-mode
/// surface: dark ink on white, violet accents.
class StatementPdfBuilder {
  const StatementPdfBuilder();

  static const _accent = PdfColor.fromInt(0xFF6C5CE7);
  static const _ink = PdfColor.fromInt(0xFF11151E);
  static const _muted = PdfColor.fromInt(0xFF5B6472);
  static const _hairline = PdfColor.fromInt(0xFFE4E7EC);

  static final _date = DateFormat('d MMM yyyy');

  Future<Uint8List> build({
    required Account account,
    required StatementDetail detail,
  }) async {
    final base =
        pw.Font.ttf(await rootBundle.load('assets/fonts/Inter-Regular.ttf'));
    final semiBold =
        pw.Font.ttf(await rootBundle.load('assets/fonts/Inter-SemiBold.ttf'));
    final bold =
        pw.Font.ttf(await rootBundle.load('assets/fonts/Inter-Bold.ttf'));

    final statement = detail.statement;
    final zero = Money.zero(statement.opening.currency);
    var totalIn = zero;
    var totalOut = zero;
    for (final line in detail.lines) {
      if (line.amount.isNegative) {
        totalOut = totalOut + line.amount;
      } else {
        totalIn = totalIn + line.amount;
      }
    }

    final period = '${_date.format(statement.periodStart)} \u2013 '
        '${_date.format(statement.periodEnd)}';

    final document = pw.Document(
      theme: pw.ThemeData.withFont(base: base, bold: bold),
    );
    // Kept as two statements rather than a cascade: the cascade form
    // fights dart format on the trailing MultiPage closure.
    // ignore: cascade_invocations
    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.symmetric(horizontal: 42, vertical: 48),
        footer: (context) => pw.Padding(
          padding: const pw.EdgeInsets.only(top: 12),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Vaulta \u2014 not an official bank document',
                style: pw.TextStyle(font: base, fontSize: 8, color: _muted),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(font: base, fontSize: 8, color: _muted),
              ),
            ],
          ),
        ),
        build: (context) => [
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Vaulta',
                style:
                    pw.TextStyle(font: semiBold, fontSize: 20, color: _accent),
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  pw.Text(
                    'Account statement',
                    style:
                        pw.TextStyle(font: semiBold, fontSize: 12, color: _ink),
                  ),
                  pw.SizedBox(height: 2),
                  pw.Text(
                    period,
                    style: pw.TextStyle(
                      font: base,
                      fontSize: 10,
                      color: _muted,
                    ),
                  ),
                ],
              ),
            ],
          ),
          pw.SizedBox(height: 20),
          pw.Text(
            account.name,
            style: pw.TextStyle(font: semiBold, fontSize: 13, color: _ink),
          ),
          pw.SizedBox(height: 2),
          pw.Text(
            account.ibanGrouped,
            style: pw.TextStyle(font: base, fontSize: 10, color: _muted),
          ),
          pw.Text(
            '${account.currency.code} \u00b7 ${account.type.label} account',
            style: pw.TextStyle(font: base, fontSize: 10, color: _muted),
          ),
          pw.SizedBox(height: 16),
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: _hairline),
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                _summaryCell(
                  base,
                  semiBold,
                  'Opening balance',
                  statement.opening.format(),
                ),
                _summaryCell(base, semiBold, 'Money in', totalIn.format()),
                _summaryCell(base, semiBold, 'Money out', totalOut.format()),
                _summaryCell(
                  base,
                  semiBold,
                  'Closing balance',
                  statement.closing.format(),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 18),
          pw.TableHelper.fromTextArray(
            headers: ['Date', 'Description', 'Amount'],
            data: [
              for (final line in detail.lines)
                [
                  _date.format(line.occurredAt),
                  line.title,
                  line.amount.formatSigned(),
                ],
            ],
            border: null,
            headerStyle:
                pw.TextStyle(font: semiBold, fontSize: 9, color: _muted),
            cellStyle: pw.TextStyle(font: base, fontSize: 9.5, color: _ink),
            columnWidths: {
              0: const pw.FixedColumnWidth(80),
              1: const pw.FlexColumnWidth(),
              2: const pw.FixedColumnWidth(95),
            },
            cellAlignments: {2: pw.Alignment.centerRight},
            headerAlignments: {2: pw.Alignment.centerRight},
            headerDecoration: const pw.BoxDecoration(
              border: pw.Border(
                bottom: pw.BorderSide(color: _muted, width: 0.5),
              ),
            ),
            rowDecoration: const pw.BoxDecoration(
              border: pw.Border(
                bottom: pw.BorderSide(color: _hairline, width: 0.4),
              ),
            ),
            cellPadding:
                const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 4),
          ),
        ],
      ),
    );

    return document.save();
  }

  pw.Widget _summaryCell(
    pw.Font base,
    pw.Font semiBold,
    String label,
    String value,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          label,
          style: pw.TextStyle(font: base, fontSize: 8, color: _muted),
        ),
        pw.SizedBox(height: 3),
        pw.Text(
          value,
          style: pw.TextStyle(font: semiBold, fontSize: 10.5, color: _ink),
        ),
      ],
    );
  }
}
